creation_rules:
  - key_groups:
      - age:
          - age143vkm327maclfkdqca4s6tufftej0hsm5hqkqq6lcd9w5vpewcyq2ph8vy # macbook
          - age149rkxrsqeke4wqnhvvz3me5vprjtcy5elg5szy4aarxrryv8m3kqvs9dme # hetzner vps
