creation_rules:
  - key_groups:
      - age:
          - age1uv373nw7sy5cjqq6nrsey674yyt0xyfwneefng9jsqwyxn5smewsawfwx7 # macbook pro
          - age143vkm327maclfkdqca4s6tufftej0hsm5hqkqq6lcd9w5vpewcyq2ph8vy # macbook air
          - age1ag242p25klsujth8xn8gjxh796wyyusdrvw955f0yrn2m5vmy9qqm6vtdq # vps
