creation_rules:
  - key_groups:
      - age:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJW+GQk0KCvSreL+y3AZdtCu82+13E2eEled+sGRkIEv macbook-pro
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHpF8kTXaBHTZqKfmEsKTILSxQYpPenI7wyMK0qTNE8y vps
          - age143vkm327maclfkdqca4s6tufftej0hsm5hqkqq6lcd9w5vpewcyq2ph8vy # macbook air
          - age1ag242p25klsujth8xn8gjxh796wyyusdrvw955f0yrn2m5vmy9qqm6vtdq # vps
          - age1z4zkxvjt5ersauvkvuyyhngpwu7qv38ygggak9jn0x9ljs5ejfcqvxnzr3 # codespace
